Repository flexcompute/tidy3d, pull requests merged in 2023-02, with the labels that each got.

#678 Phase 1: self-intersecting polyslab
  tests/test_components/test_sidewall.py
  tests/test_plugins/test_polyslab.py
  tidy3d/components/geometry.py
  tidy3d/plugins/__init__.py
  tidy3d/plugins/adjoint/components/geometry.py
  tidy3d/plugins/polyslab/__init__.py
  tidy3d/plugins/polyslab/polyslab.py
Labels: 1.9, rc2

#684 fixes for 1.9.0rc2 docs
  tidy3d/components/data/sim_data.py
  tidy3d/components/geometry.py
Labels: 1.9, rc2

#683 Try gdspy vertices loading if gdstk loading fails
  MANIFEST.in
  requirements/dev.txt
  requirements/gdspy.txt
  requirements/gdstk.txt
  setup.py
  tests/test_components/test_geometry.py
  tidy3d/components/geometry.py
  tox.ini
Labels: 1.9, rc2

#662 Casey/2dmaterials
  tests/test_components/test_medium.py
  tests/test_components/test_simulation.py
  tests/test_package/test_material_library.py
  tests/test_package/test_parametric_variants.py
  tidy3d/__init__.py
  tidy3d/components/grid/mesher.py
  tidy3d/components/medium.py
  tidy3d/components/monitor.py
  tidy3d/components/simulation.py
  tidy3d/components/structure.py
  tidy3d/constants.py
  tidy3d/material_library/material_library.py
  tidy3d/material_library/material_reference.py
  tidy3d/material_library/parametric_materials.py
Labels: rc1, 1.10

#702 `web.run_async` as alternative to `web.Batch`
  CHANGELOG.md
  tests/_test_local/_test_web.py
  tests/sims/simulation_1_9_0rc2.json
  tidy3d/web/__init__.py
  tidy3d/web/queue.py
Labels: 1.9

#705 warn in `sim.epsilon` if too many grid cells
  CHANGELOG.md
  tests/test_components/test_simulation.py
  tidy3d/components/simulation.py
Labels: 1.9

#693 2D simulation boundary warning
  CHANGELOG.md
  tests/test_components/test_simulation.py
  tidy3d/components/simulation.py
Labels: 1.9

#707 assert_log_level takes level string instead of int
  tests/test_components/test_boundaries.py
  tests/test_components/test_custom.py
  tests/test_components/test_geometry.py
  tests/test_components/test_simulation.py
  tests/test_data/test_monitor_data.py
  tests/test_plugins/test_adjoint.py
  tests/test_plugins/test_polyslab.py
  tests/utils.py
Labels: 1.9

#706 force progress bars to 100% when task completed
  CHANGELOG.md
  tidy3d/web/container.py
  tidy3d/web/s3utils.py
  tidy3d/web/webapi.py
Labels: 1.9

#703 Reorganize geometry.inside and intersection methods for some speed improvements
  .pylintrc
  CHANGELOG.md
  tests/test_components/test_geometry.py
  tests/test_components/test_simulation.py
  tidy3d/components/geometry.py
  tidy3d/components/simulation.py
Labels: 1.9

#708 refactor Box.surfaces and Source.injection_axis
  tidy3d/components/boundary.py
  tidy3d/components/simulation.py
  tidy3d/components/source.py
Labels: 1.9

#694 verbose option in webapi
  tests/test_web/test_webapi.py
  tidy3d/web/container.py
  tidy3d/web/s3utils.py
  tidy3d/web/webapi.py
Labels: 1.9

#713 fix determinant warning
  CHANGELOG.md
  tidy3d/plugins/mode/solver.py
Labels: 1.9

#724 Limit the maximum number of grid size too small warnings
  CHANGELOG.md
  tests/sims/simulation_1_9_0.json
  tidy3d/components/simulation.py
Labels: 1.9

#714 Add arrow curvature to sources and monitors with bend radius (#272)
  CHANGELOG.md
  tidy3d/components/geometry.py
  tidy3d/components/monitor.py
  tidy3d/components/source.py
  tidy3d/components/viz.py
Labels: 1.9

#729 Small conceptual change to constants definitions
  tidy3d/constants.py
Labels: improvement
