Repository flexcompute/tidy3d, pull requests merged in 2023-10, with the labels that each got.

#1187 better description for TimeMonitor.interval
  CHANGELOG.md
  tests/test_components/test_monitor.py
  tidy3d/components/monitor.py
Labels: 2.4

#1083 Heat solver interface
  CHANGELOG.md
  tests/sims/simulation_2_5_0rc1.json
  tests/test_components/test_bc_placement.py
  tests/test_components/test_heat.py
  tests/test_components/test_scene.py
  tests/test_components/test_simulation.py
  tests/test_web/test_webapi_heat.py
  tests/utils.py
  tidy3d/__init__.py
  tidy3d/components/base.py
  tidy3d/components/base_sim/__init__.py
  tidy3d/components/base_sim/data/__init__.py
  tidy3d/components/base_sim/data/monitor_data.py
  tidy3d/components/base_sim/data/sim_data.py
  tidy3d/components/base_sim/monitor.py
  tidy3d/components/base_sim/simulation.py
  tidy3d/components/bc_placement.py
  tidy3d/components/data/data_array.py
  tidy3d/components/data/sim_data.py
  tidy3d/components/geometry/base.py
  tidy3d/components/geometry/utils.py
  tidy3d/components/heat/__init__.py
  tidy3d/components/heat/boundary.py
  tidy3d/components/heat/data/__init__.py
  tidy3d/components/heat/data/monitor_data.py
  tidy3d/components/heat/data/sim_data.py
  tidy3d/components/heat/grid.py
  tidy3d/components/heat/monitor.py
  tidy3d/components/heat/simulation.py
  tidy3d/components/heat/source.py
  tidy3d/components/heat/viz.py
  tidy3d/components/heat_spec.py
  tidy3d/components/medium.py
  tidy3d/components/monitor.py
  tidy3d/components/scene.py
  tidy3d/components/simulation.py
  tidy3d/components/types.py
  tidy3d/components/viz.py
  tidy3d/constants.py
  tidy3d/web/api/asynchronous.py
  tidy3d/web/api/container.py
  tidy3d/web/api/tidy3d_stub.py
  tidy3d/web/api/webapi.py
  tidy3d/web/environment.py
Labels: 2.5

#1195 add divergence mention to PML warning
  tidy3d/components/simulation.py
Labels: 2.5

#1178 Issue a warning when accessing unavailable group index data (#1169)
  tests/test_plugins/test_mode_solver.py
  tidy3d/components/data/dataset.py
  tidy3d/components/data/monitor_data.py
Labels: 2.5

#1202 Limit number of sources to 1000
  CHANGELOG.md
  tests/test_components/test_simulation.py
  tidy3d/components/simulation.py
Labels: 2.4

#1201 Test initialization speed of a metalens with 10_000 structures
  CHANGELOG.md
  tidy3d/components/geometry/base.py
  tidy3d/components/simulation.py
Labels: 2.4

#1200 Fix updater for hdf5 files with custom data, and add hdf5 files to automatic updater testing
  CHANGELOG.md
  tests/sims/simulation_2_4_2.h5
  tests/test_components/test_IO.py
  tidy3d/components/base.py
  tidy3d/updater.py
Labels: 2.4

#1192 broadband adjoint (2.5)
  CHANGELOG.md
  tests/test_plugins/test_adjoint.py
  tidy3d/components/source.py
  tidy3d/plugins/adjoint/components/data/monitor_data.py
  tidy3d/plugins/adjoint/components/data/sim_data.py
  tidy3d/plugins/adjoint/components/geometry.py
  tidy3d/plugins/adjoint/components/medium.py
  tidy3d/plugins/adjoint/components/simulation.py
  tidy3d/plugins/adjoint/components/structure.py
  tidy3d/plugins/adjoint/web.py
Labels: 2.5

#1210 unpin boto and click
  CHANGELOG.md
  requirements/web.txt
Labels: 2.5

#1188 Space-time modulation of all types of materials
  CHANGELOG.md
  tests/test_components/test_time_modulation.py
  tidy3d/__init__.py
  tidy3d/components/medium.py
  tidy3d/components/simulation.py
  tidy3d/components/source.py
  tidy3d/components/time.py
  tidy3d/components/time_modulation.py
Labels: 2.5

#1221 Error instead of warning for zero-dim boundaries not periodic or Bloch
  CHANGELOG.md
  tests/test_components/test_simulation.py
  tests/test_plugins/test_adjoint.py
  tidy3d/components/simulation.py
Labels: rc3

#1227 Truncate circular filter in edge case
  CHANGELOG.md
  tests/test_plugins/test_adjoint.py
  tidy3d/plugins/adjoint/utils/filter.py
Labels: 2.5
