Repository flexcompute/tidy3d, pull requests merged in 2023-06, with the labels that each got.

#870 Custom dispersive medium
  CHANGELOG.md
  tests/test_components/test_custom.py
  tidy3d/__init__.py
  tidy3d/components/base.py
  tidy3d/components/data/data_array.py
  tidy3d/components/medium.py
  tidy3d/components/simulation.py
  tidy3d/components/structure.py
  tidy3d/plugins/adjoint/components/data/data_array.py
  tidy3d/plugins/adjoint/components/medium.py
Labels: 2.3

#920 Tyler/source/custom current fix
  tidy3d/components/simulation.py
Labels: 2.3

#922 Retry connection in adjiont web functions
  tidy3d/plugins/adjoint/web.py
Labels: 2.3

#929 Add "allow_gain" in Medium that allows for gain medium when it is True
  CHANGELOG.md
  tests/test_components/test_custom.py
  tests/test_components/test_medium.py
  tests/test_components/test_simulation.py
  tidy3d/components/medium.py
  tidy3d/plugins/adjoint/components/medium.py
Labels: 2.3

#945 remove adjoint grad_eps monitors
  CHANGELOG.md
  tidy3d/plugins/adjoint/components/data/sim_data.py
  tidy3d/plugins/adjoint/components/simulation.py
Labels: 2.3

#868 Enable access to remote mode solver from python
  CHANGELOG.md
  tests/test_package/test_log.py
  tests/test_plugins/test_mode_solver.py
  tests/test_web/test_webapi.py
  tidy3d/components/data/monitor_data.py
  tidy3d/components/mode.py
  tidy3d/plugins/mode/mode_solver.py
  tidy3d/plugins/mode/web.py
  tidy3d/plugins/waveguide/rectangular_dielectric.py
  tidy3d/web/s3utils.py
  tidy3d/web/simulation_task.py
  tidy3d/web/webapi.py
Labels: WIP, 2.3

#971 remove restriction on 3D pixelated grids in JaxCustomMedium
  CHANGELOG.md
  tests/test_plugins/test_adjoint.py
  tidy3d/plugins/adjoint/components/medium.py
Labels: adjoint 2.3

#970 restrict number of adjoint input structures
  CHANGELOG.md
  tests/test_plugins/test_adjoint.py
  tidy3d/plugins/adjoint/components/simulation.py
Labels: adjoint 2.3

#980 Fix pydantic related allow_gain warning in AnisotropicMedium
  tidy3d/components/medium.py
Labels: 2.3
