Repository flexcompute/tidy3d, pull requests merged in 2023-03, with the labels that each got.

#736 fix sphinx build error because of confusing queue.py with queue package
  tidy3d/plugins/adjoint/web.py
  tidy3d/web/__init__.py
  tidy3d/web/asynchronous.py
Labels: Bug, 1.9

#735 fix a bug in web.monitor that continued before run monitor
  tidy3d/web/webapi.py
Labels: Bug, 1.9

#742 set rich < 12.6.0 to fix double progressbars
  CHANGELOG.md
  requirements/basic.txt
Labels: 1.9

#700 STL Import
  MANIFEST.in
  requirements/dev.txt
  requirements/surfacemesh.txt
  setup.py
  tests/data/tetrahedron.stl
  tests/sims/simulation_1_9_0.json
  tests/sims/simulation_1_9_0rc2.json
  tests/test_components/test_IO.py
  tests/test_components/test_geometry.py
  tests/utils.py
  tidy3d/__init__.py
  tidy3d/components/data/data_array.py
  tidy3d/components/data/dataset.py
  tidy3d/components/geometry.py
  tidy3d/components/simulation.py
  tox.ini
Labels: 1.10

#750 update s3 client to use override ssl verify
  CHANGELOG.md
  tidy3d/web/s3utils.py
Labels: rc2, 1.10

#749 adds "val" option in `SourceTime` plotting
  CHANGELOG.md
  tests/test_components/test_source.py
  tidy3d/components/data/sim_data.py
  tidy3d/components/source.py
  tidy3d/components/types.py
Labels: rc2, 1.10

#752 Include material name in material_library's export_matlib_to_file
  CHANGELOG.md
  tidy3d/material_library/material_library.py
Labels: rc2, 1.10

#758 validator to error if JaxSimulation provided to SimulationTask
  tests/test_plugins/test_adjoint.py
  tidy3d/web/simulation_task.py
Labels: rc2, 1.10

#732 Ignore some mediums in mesher
  tidy3d/components/grid/mesher.py
Labels: 1.10

#688 Convert mode solver.py into a class
  tidy3d/components/types.py
  tidy3d/plugins/mode/solver.py
Labels: 1.10

#766 remove WIP features from adjoint types to avoid confusion
  tests/test_plugins/test_adjoint.py
  tidy3d/plugins/adjoint/components/data/monitor_data.py
  tidy3d/plugins/adjoint/components/geometry.py
Labels: 1.10

#771 use webapi for get_run_info
  tests/test_web/test_tidy3d_task.py
  tests/test_web/test_webapi.py
  tidy3d/web/simulation_task.py
Labels: 1.10

#772 remove a broken adjoint test
  tests/test_plugins/test_adjoint.py
Labels: 1.10

#762 Extra field plot options
  CHANGELOG.md
  tests/test_data/test_sim_data.py
  tidy3d/components/data/README.md
  tidy3d/components/data/sim_data.py
  tidy3d/components/types.py
  tidy3d/plugins/mode/mode_solver.py
Labels: 1.10

#748 revamped ArrayLike
  CHANGELOG.md
  tests/test_components/test_types.py
  tidy3d/components/apodization.py
  tidy3d/components/base.py
  tidy3d/components/data/monitor_data.py
  tidy3d/components/field_projection.py
  tidy3d/components/geometry.py
  tidy3d/components/grid/grid.py
  tidy3d/components/grid/mesher.py
  tidy3d/components/medium.py
  tidy3d/components/monitor.py
  tidy3d/components/source.py
  tidy3d/components/types.py
  tidy3d/plugins/adjoint/components/geometry.py
  tidy3d/plugins/dispersion/fit.py
  tidy3d/plugins/mode/mode_solver.py
  tidy3d/plugins/resonance/resonance.py
Labels: rc2, 1.10

#774 add post init validators and check if structures terminate in PML
  CHANGELOG.md
  requirements/basic.txt
  tests/test_components/test_simulation.py
  tidy3d/components/base.py
  tidy3d/components/simulation.py
Labels: 1.10

#789 update readme instructions on environment variable API key
  README.md
Labels: 1.10

#792 fix pml validator
  tidy3d/components/simulation.py
Labels: 1.10

#791 Tyler changelog additions 1.10
  CHANGELOG.md
Labels: 1.10

#782 Some updates to grid and mesher
  tests/test_components/test_grid.py
  tests/test_components/test_grid_spec.py
  tidy3d/components/boundary.py
  tidy3d/components/grid/grid.py
  tidy3d/components/grid/grid_spec.py
  tidy3d/components/simulation.py
Labels: 1.10

#790 Treat infinite slanted cylinder and add validators
  CHANGELOG.md
  tests/test_components/test_geometry.py
  tests/test_components/test_sidewall.py
  tidy3d/components/geometry.py
Labels: 1.10

#794 update README and set PIP_NAME to "tidy3d"
  CHANGELOG.md
  README.md
  setup.py
  tidy3d/__init__.py
  tidy3d/version.py
Labels: 2.0

#804 fix plugin imports
  tests/_test_local/_test_fit_web.py
  tests/_test_local/_test_plugins_web.py
  tidy3d/plugins/resonance/resonance.py
  tidy3d/web/cli/readme.md
Labels: 2.0

#793 API changes for 2.0
  CHANGELOG.md
  tests/sims/simulation_1_10_0rc2.json
  tests/test_components/test_boundaries.py
  tests/test_components/test_custom.py
  tests/test_components/test_geometry.py
  tests/test_components/test_sidewall.py
  tests/test_components/test_simulation.py
  tests/test_data/test_monitor_data.py
  tests/test_package/test_log.py
  tests/test_plugins/test_adjoint.py
  tests/test_plugins/test_polyslab.py
  tidy3d/components/boundary.py
  tidy3d/components/geometry.py
  tidy3d/components/simulation.py
  tidy3d/config.py
  tidy3d/log.py
  tidy3d/plugins/polyslab/polyslab.py
Labels: 2.0

#809 FlexUnit -> FlexCredit
  tidy3d/web/simulation_task.py
  tidy3d/web/webapi.py
Labels: 2.0

#803 better readme instructions for 2.0
  README.md
Labels: 2.0

#812 Unpinning importlib-metadata version
  CHANGELOG.md
  requirements/basic.txt
Labels: 2.1

#815 set verbose=True by default in webapi
  CHANGELOG.md
  tests/sims/simulation_2_0_0.json
  tidy3d/plugins/adjoint/web.py
  tidy3d/web/asynchronous.py
  tidy3d/web/container.py
  tidy3d/web/s3utils.py
  tidy3d/web/simulation_task.py
  tidy3d/web/webapi.py
Labels: 2.0
