Repository flexcompute/tidy3d, pull requests merged in 2024-07, with the labels that each got.

#1724 Introduce the DirectivityMonitor and DirectivityData classes
  CHANGELOG.md
  docs/api/monitors.rst
  docs/api/output_data.rst
  tests/test_components/test_monitor.py
  tests/test_data/test_data_arrays.py
  tests/test_data/test_monitor_data.py
  tests/test_data/test_sim_data.py
  tests/utils.py
  tidy3d/__init__.py
  tidy3d/components/data/data_array.py
  tidy3d/components/data/monitor_data.py
  tidy3d/components/monitor.py
Labels: awaiting backend, 2.8

#1799 add `RunTimeSpec` to API ref
  docs/api/simulation.rst
Labels: 2.7

#1801 fix box gradients < 3d
  CHANGELOG.md
  tidy3d/components/autograd/derivative_utils.py
Labels: 2.7

#1798 Docstring - HeatCharge docstring error
  tidy3d/components/heat_charge/heat/simulation.py
  tidy3d/components/heat_charge/source.py
  tidy3d/components/heat_charge_spec.py
Labels: 2.8

#1769 Differentiable n-dimensional `nearest` and `linear` interpolation for `DataArray`
  CHANGELOG.md
  tests/test_components/test_autograd.py
  tests/test_plugins/autograd/test_functions.py
  tests/test_plugins/test_microwave.py
  tests/utils.py
  tidy3d/components/autograd/__init__.py
  tidy3d/components/autograd/derivative_utils.py
  tidy3d/components/autograd/functions.py
  tidy3d/components/autograd/types.py
  tidy3d/components/base.py
  tidy3d/components/data/data_array.py
  tidy3d/components/data/monitor_data.py
  tidy3d/plugins/autograd/functions.py
  tidy3d/plugins/autograd/invdes/filters.py
  tidy3d/plugins/autograd/invdes/misc.py
  tidy3d/plugins/autograd/invdes/parametrizations.py
  tidy3d/plugins/autograd/invdes/penalties.py
  tidy3d/plugins/autograd/invdes/projections.py
  tidy3d/plugins/autograd/utilities.py
Labels: 2.7, .1

#1805 :wrench: Correct sync between frontend and docs
  .github/workflows/sync-to-readthedocs-repo.yaml
Labels: 2.7

#1819 Making _esp_bounds and _get_structure_eps_plot_params static methods
  tidy3d/components/scene.py
Labels: 2.7

#1820 Speeding up num_mediums test
  tests/test_components/test_simulation.py
Labels: 2.7

#1817 Fix bug in loading previously run Batch and ComponentModeler from file when custom medium present
  CHANGELOG.md
  tidy3d/plugins/smatrix/component_modelers/base.py
  tidy3d/web/api/container.py
Labels: 2.7, .2

#1818 Fixing DataArray.tracers for zero-sized data
  tidy3d/components/data/data_array.py
Labels: 2.7

#1639 Fix near2far for 2d simulations
  CHANGELOG.md
  tests/test_components/test_simulation.py
  tidy3d/components/data/monitor_data.py
  tidy3d/components/field_projection.py
  tidy3d/components/simulation.py
Labels: 2.7, .2

#1839 Fixed bug in HeatChargeSimulation.plot() when we have global sources
  tidy3d/components/heat_charge/simulation.py
Labels: 2.8

#1814 Improved mesh repair options in TriangleMesh
  CHANGELOG.md
  tests/test_components/test_geometry.py
  tidy3d/components/geometry/mesh.py
Labels: 2.7

#1841 HeatChargeSimulation backward compatibility
  tidy3d/components/heat_charge/boundary.py
  tidy3d/components/heat_charge/simulation.py
Labels: 2.8

#1741 add WavePorts
  CHANGELOG.md
  docs/api/plugins/smatrix.rst
  tests/test_plugins/terminal_component_modeler_def.py
  tests/test_plugins/test_microwave.py
  tests/test_plugins/test_terminal_component_modeler.py
  tidy3d/components/data/monitor_data.py
  tidy3d/components/geometry/base.py
  tidy3d/components/viz.py
  tidy3d/constants.py
  tidy3d/plugins/microwave/__init__.py
  tidy3d/plugins/microwave/custom_path_integrals.py
  tidy3d/plugins/microwave/impedance_calculator.py
  tidy3d/plugins/microwave/path_integrals.py
  tidy3d/plugins/microwave/viz.py
  tidy3d/plugins/smatrix/__init__.py
  tidy3d/plugins/smatrix/component_modelers/base.py
  tidy3d/plugins/smatrix/component_modelers/modal.py
  tidy3d/plugins/smatrix/component_modelers/terminal.py
  tidy3d/plugins/smatrix/ports/base_lumped.py
  tidy3d/plugins/smatrix/ports/base_terminal.py
  tidy3d/plugins/smatrix/ports/coaxial_lumped.py
  tidy3d/plugins/smatrix/ports/rectangular_lumped.py
  tidy3d/plugins/smatrix/ports/wave.py
Labels: 2.8

#1830 🗻 autograd: broadband objectives with single adjoint simulation
  CHANGELOG.md
  tests/test_components/test_autograd.py
  tests/utils.py
  tidy3d/components/data/monitor_data.py
  tidy3d/components/data/sim_data.py
  tidy3d/components/medium.py
  tidy3d/components/simulation.py
  tidy3d/components/source.py
  tidy3d/web/api/autograd/autograd.py
Labels: 2.7, .2
