Repository flexcompute/tidy3d, pull requests merged in 2024-08, with the labels that each got.

#1855 :books: Fix image rendering
  tidy3d/plugins/invdes/transformation.py
Labels: 2.7, .2

#1868 add units to `IndexPerturbation.frequency`
  tidy3d/components/parameter_perturbation.py
Labels: 2.7, .2

#1894 Improve passivity enforcement near high-Q poles in FastDispersionFitter
  CHANGELOG.md
  tests/test_plugins/test_dispersion_fitter.py
  tidy3d/plugins/dispersion/fit_fast.py
Labels: 2.7

#1917 🗻 better error when flux monitor used in autograd
  CHANGELOG.md
  tests/test_components/test_autograd.py
  tests/utils.py
  tidy3d/components/data/monitor_data.py
Labels: 2.7, .3

#1920 fixes bug if traced cylinders are inovled in intersections
  tests/test_components/test_autograd.py
  tests/utils.py
  tidy3d/components/geometry/primitives.py
Labels: 2.7, .3

#1925 Bump to xarray>=2023.08.0
  poetry.lock
  pyproject.toml
Labels: 2.7, .3
