Repository flexcompute/tidy3d, pull requests merged in 2024-05, with the labels that each got.

#1630 batch refactoring / multi-threading
  CHANGELOG.md
  tests/test_web/test_webapi.py
  tidy3d/plugins/adjoint/web.py
  tidy3d/web/api/container.py
Labels: 2.7

#1493 Add metadata to Tidy3D components
  CHANGELOG.md
  tests/test_components/test_base.py
  tests/test_components/test_grid.py
  tidy3d/components/base.py
  tidy3d/components/grid/grid.py
  tidy3d/components/viz.py
Labels: rc2, 2.7

#1495 Simulation.run_time accepts RunTimeSpec
  CHANGELOG.md
  tests/test_components/test_simulation.py
  tidy3d/__init__.py
  tidy3d/components/run_time_spec.py
  tidy3d/components/simulation.py
  tidy3d/components/source.py
  tidy3d/plugins/adjoint/components/simulation.py
Labels: rc2, 2.7

#1672 Fast Dispersion Fitter: keep poles slightly away from input freqs
  CHANGELOG.md
  tests/test_plugins/test_dispersion_fitter.py
  tidy3d/plugins/dispersion/fit_fast.py
Labels: rc2, 2.7

#1679 Relax smallest triangle area in TriangleMesh to 1e-36
  CHANGELOG.md
  tests/test_components/test_geometry.py
  tidy3d/components/geometry/mesh.py
Labels: rc2, awaiting backend, 2.7

#1688 TEST: fix medium test comparison
  tests/test_components/test_custom.py
Labels: Bug

#1634 Show cost for EME, HEAT, and MODE. Remove URL from EME webapi.
  tidy3d/web/api/webapi.py
Labels: 2.7

#1686 Adding num_proc arg to adjoint run_local, and properly avoiding validators
  CHANGELOG.md
  tests/test_plugins/test_adjoint.py
  tidy3d/plugins/adjoint/web.py
Labels: rc2, 2.7

#1694 Fix pol vector
  tests/test_components/test_source.py
  tidy3d/components/source.py
Labels: rc2, 2.7

#1698 `JaxComplexPolySlab` support
  CHANGELOG.md
  tests/test_plugins/test_adjoint.py
  tidy3d/plugins/adjoint/__init__.py
  tidy3d/plugins/adjoint/components/__init__.py
  tidy3d/plugins/adjoint/components/geometry.py
Labels: rc2, 2.7

#1685 Mode solver `run_batch`
  CHANGELOG.md
  tests/test_plugins/test_mode_solver.py
  tidy3d/plugins/mode/web.py
  tidy3d/web/api/mode.py
Labels: 2.7

#1689 Introduce SubpixelSpec to allow for selecting subpixel averaging methods on different materials
  CHANGELOG.md
  docs/api/discretization.rst
  docs/api/index.rst
  docs/api/subpixel_averaging.rst
  tests/sims/simulation_sample.h5
  tests/sims/simulation_sample.json
  tests/test_components/test_simulation.py
  tidy3d/__init__.py
  tidy3d/components/eme/simulation.py
  tidy3d/components/grid/grid_spec.py
  tidy3d/components/medium.py
  tidy3d/components/simulation.py
  tidy3d/components/subpixel_spec.py
  tidy3d/plugins/adjoint/components/simulation.py
Labels: awaiting backend, 2.7, blocking

#1727 fix edge case adjoint if maximum refractive index=0 (eg for dispersive materials)
  CHANGELOG.md
  tidy3d/plugins/adjoint/components/structure.py
Labels: 2.7, blocking

#1728 100% coverage for autograd core
  tests/test_components/test_autograd.py
Labels: 2.7

#1726 more robust `Batch.monitor` if run status missing
  CHANGELOG.md
  tidy3d/web/api/container.py
Labels: 2.7, blocking
