Repository flexcompute/tidy3d, pull requests merged in 2024-02, with the labels that each got.

#1329 Added free-carrier absorption (FCA) and free-carrier plasma dispersion (FCPD)
  CHANGELOG.md
  tests/sims/simulation_2_6_0rc1.json
  tests/test_components/test_medium.py
  tests/utils.py
  tidy3d/components/medium.py
  tidy3d/schema.json
Labels: awaiting backend

#1452 fix for innhomegenous substrates/superstrates in 1D and 2D simulations
  tidy3d/components/simulation.py
Labels: Bug

#1285 Support conformal mesh for PEC structures
  CHANGELOG.md
  tests/test_components/test_simulation.py
  tidy3d/__init__.py
  tidy3d/components/grid/grid_spec.py
  tidy3d/components/simulation.py
  tidy3d/plugins/mode/mode_solver.py
  tidy3d/plugins/mode/solver.py
Labels: awaiting backend

#1467 adjoint util erosion-dilation penalty
  CHANGELOG.md
  tests/test_plugins/test_adjoint.py
  tidy3d/plugins/adjoint/utils/penalty.py
Labels: 2.6

#1465 Improved efficiency of overlap_sort
  tidy3d/components/data/monitor_data.py
Labels: 2.6

#1470 Updates to help unify backend logging (Reset back to original #1457)
  CHANGELOG.md
  tidy3d/components/data/monitor_data.py
  tidy3d/config.py
  tidy3d/log.py
  tidy3d/plugins/adjoint/components/simulation.py
Labels: 2.6

#1484 Add uniaxial medium lithium niobate to material library
  CHANGELOG.md
  docs/api/material_library.rst
  docs/generate_doc.py
  tests/test_package/test_material_library.py
  tidy3d/material_library/material_library.py
  tidy3d/material_library/material_reference.py
Labels: 2.6

#1473 more accurate adjoint run_time
  CHANGELOG.md
  tests/test_plugins/test_adjoint.py
  tidy3d/plugins/adjoint/components/simulation.py
Labels: 2.7

#1490 Fix to monitor discretize inds if there's an empty set along at least…
  CHANGELOG.md
  tidy3d/components/simulation.py
Labels: 2.6

#1474 Validate that incompatible advanced materials don't intersect
  CHANGELOG.md
  tests/sims/simulation_2_5_1.h5
  tests/sims/simulation_2_5_1.json
  tests/sims/simulation_sample.h5
  tests/sims/simulation_sample.json
  tests/test_components/test_medium.py
  tests/test_components/test_simulation.py
  tests/test_components/test_time_modulation.py
  tests/utils.py
  tidy3d/components/medium.py
  tidy3d/components/scene.py
  tidy3d/components/simulation.py
  tidy3d/components/structure.py
Labels: 2.6

#1471 RF feature (Hold to merge to pre/2.7 branch)
  CHANGELOG.md
  docs/api/discretization.rst
  tests/test_components/test_simulation.py
  tidy3d/__init__.py
  tidy3d/components/grid/grid_spec.py
  tidy3d/components/simulation.py
  tidy3d/plugins/mode/mode_solver.py
  tidy3d/plugins/mode/solver.py
Labels: 2.7

#1502 fix pec freq arg
  CHANGELOG.md
  tidy3d/components/medium.py
Labels: Bug
