Repository flexcompute/tidy3d, pull requests merged in 2024-04, with the labels that each got.

#1542 FEAT: Compute characteristic impedance from fields
  CHANGELOG.md
  docs/api/plugins/index.rst
  docs/api/plugins/microwave.rst
  tests/test_plugins/test_microwave.py
  tests/utils.py
  tidy3d/components/validators.py
  tidy3d/plugins/microwave/__init__.py
  tidy3d/plugins/microwave/impedance_calculator.py
  tidy3d/plugins/microwave/path_integrals.py
  tidy3d/plugins/smatrix/component_modelers/terminal.py
  tidy3d/plugins/smatrix/ports/lumped.py
Labels: feature, RF

#1605 fix interpolation for unstructured data
  tidy3d/components/data/dataset.py
Labels: 2.7

#1589 mkdirs in to_gds_file calls if they dont exist
  CHANGELOG.md
  tidy3d/components/geometry/base.py
  tidy3d/components/simulation.py
  tidy3d/components/structure.py
Labels: 2.7

#1601 Fix `JaxSimulation.epsilon` to include all `input_structures`
  CHANGELOG.md
  tidy3d/components/simulation.py
  tidy3d/plugins/adjoint/components/simulation.py
Labels: 2.7

#1608 JaxSimulation properties to check adjoint run_time
  CHANGELOG.md
  tests/test_plugins/test_adjoint.py
  tidy3d/plugins/adjoint/components/simulation.py
Labels: 2.7

#1594 Recursive `updated_copy()` of nested components with `path`
  CHANGELOG.md
  tests/test_components/test_base.py
  tidy3d/components/base.py
Labels: 2.7

#1606 fix field data flux
  CHANGELOG.md
  tests/test_plugins/test_adjoint.py
  tidy3d/plugins/adjoint/components/data/monitor_data.py
Labels: 2.7

#1626 fix bug in `Design.run_batch()` when kwargs provided
  CHANGELOG.md
  tidy3d/plugins/design/method.py
Labels: 2.6

#1623 warning and changelog for `JaxPolySlab.vertices` no longer tracing derivatives
  CHANGELOG.md
  tests/test_plugins/test_adjoint.py
  tidy3d/plugins/adjoint/utils/penalty.py
Labels: 2.7

#1600 proper error when computing poynting vector of jax-traced field data
  CHANGELOG.md
  tests/test_plugins/test_adjoint.py
  tidy3d/plugins/adjoint/components/data/sim_data.py
Labels: 2.7

#1629 fix missing doc references for smatrix
  docs/api/plugins/smatrix.rst
  tidy3d/plugins/smatrix/component_modelers/base.py
Labels: documentation

#1555 Zero thickness for volumetric equivalence of 2D material
  tests/_test_notebooks/full_test_notebooks.py
  tests/test_components/test_grid_spec.py
  tests/test_components/test_simulation.py
  tidy3d/components/medium.py
  tidy3d/components/simulation.py
Labels: awaiting backend

#1632 :wrench: FIX: bumpmyversion pyproject.toml match
  .github/workflows/run_tests.yml
  pyproject.toml
Labels: 2.7

#1640 :package: BUILD: Update rich for flow360 full compatibility
  poetry.lock
  pyproject.toml
Labels: 2.7

#1641 support gz in updater
  CHANGELOG.md
  tidy3d/updater.py
Labels: 2.7

#1643 fix plotting of 2d objects
  CHANGELOG.md
  tidy3d/components/geometry/base.py
  tidy3d/components/geometry/polyslab.py
  tidy3d/components/geometry/primitives.py
Labels: Bug

#1638 Heat solver improvements
  tests/_test_data/_test_datasets_no_vtk.py
  tests/test_components/test_heat.py
  tests/test_data/test_data_arrays.py
  tests/test_data/test_datasets.py
  tidy3d/components/data/data_array.py
  tidy3d/components/data/dataset.py
  tidy3d/components/heat/boundary.py
  tidy3d/components/heat/data/monitor_data.py
  tidy3d/components/heat/grid.py
  tidy3d/components/heat/simulation.py
  tidy3d/components/simulation.py
Labels: 2.7

#1580 Improve mode solver PML
  CHANGELOG.md
  tidy3d/plugins/mode/derivatives.py
  tidy3d/plugins/mode/solver.py
Labels: 2.7
