Repository flexcompute/tidy3d, pull requests merged in 2024-10, with the labels that each got.

#1995 fixed bug where lumped elements were not being removed in Simulation.subsection
  CHANGELOG.md
  tests/test_components/test_simulation.py
  tests/utils.py
  tidy3d/components/simulation.py
Labels: Bug, 2.8

#2005 fix field projection discrepancy
  CHANGELOG.md
  tidy3d/components/field_projection.py
Labels: Bug

#2013 Fix metric validator for float case
  tidy3d/plugins/invdes/design.py
Labels: 2.7

#1886 Add LossyMetalMedium and subpixel options for lossy_metal including SIBC
  CHANGELOG.md
  docs/api/mediums.rst
  docs/api/subpixel_averaging.rst
  tests/test_components/test_medium.py
  tidy3d/__init__.py
  tidy3d/components/grid/mesher.py
  tidy3d/components/medium.py
  tidy3d/components/simulation.py
  tidy3d/components/subpixel_spec.py
Labels: awaiting backend, 2.8

#2032 fix: remove autograd temporary simulation files
  CHANGELOG.md
  tidy3d/plugins/adjoint/web.py
  tidy3d/web/api/autograd/autograd.py
Labels: 2.7

#2025 Autograd Dataarray rework
  CHANGELOG.md
  tests/test_components/test_autograd.py
  tests/test_components/test_structure.py
  tests/test_data/test_data_arrays.py
  tests/test_plugins/autograd/test_functions.py
  tidy3d/components/autograd/__init__.py
  tidy3d/components/autograd/boxes.py
  tidy3d/components/autograd/derivative_utils.py
  tidy3d/components/autograd/functions.py
  tidy3d/components/autograd/utils.py
  tidy3d/components/base.py
  tidy3d/components/data/data_array.py
  tidy3d/components/data/monitor_data.py
  tidy3d/components/geometry/base.py
  tidy3d/plugins/autograd/README.md
  tidy3d/plugins/expressions/metrics.py
Labels: 2.7

#1822 Differentiable local field projection
  CHANGELOG.md
  tests/ruff.toml
  tests/test_components/test_autograd.py
  tests/test_components/test_field_projection.py
  tests/test_plugins/autograd/test_functions.py
  tests/utils.py
  tidy3d/components/autograd/__init__.py
  tidy3d/components/autograd/functions.py
  tidy3d/components/data/monitor_data.py
  tidy3d/components/field_projection.py
  tidy3d/components/simulation.py
  tidy3d/plugins/autograd/README.md
  tidy3d/plugins/autograd/functions.py
Labels: 2.7, .6

#2041 fix: xarray 2023.08.0 compatibility
  tests/test_components/test_autograd.py
  tidy3d/components/autograd/boxes.py
Labels: 2.7, .6

#1980 expanded lumped elements
  CHANGELOG.md
  docs/api/abstract_models.rst
  docs/api/lumped_elements.rst
  tests/test_components/test_geometry.py
  tests/test_components/test_lumped_element.py
  tests/test_components/test_medium.py
  tests/test_plugins/smatrix/test_terminal_component_modeler.py
  tests/test_plugins/test_microwave.py
  tidy3d/__init__.py
  tidy3d/components/geometry/utils.py
  tidy3d/components/lumped_element.py
  tidy3d/components/medium.py
  tidy3d/components/simulation.py
  tidy3d/constants.py
  tidy3d/plugins/microwave/__init__.py
  tidy3d/plugins/microwave/auto_path_integrals.py
  tidy3d/plugins/smatrix/component_modelers/terminal.py
  tidy3d/plugins/smatrix/ports/base_lumped.py
  tidy3d/plugins/smatrix/ports/base_terminal.py
  tidy3d/plugins/smatrix/ports/coaxial_lumped.py
  tidy3d/plugins/smatrix/ports/rectangular_lumped.py
  tidy3d/plugins/smatrix/ports/wave.py
Labels: 2.8
