Repository flexcompute/tidy3d, pull requests merged in 2024-06, with the labels that each got.

#1684 Validate that custom datasets can interpolate
  tests/test_components/test_medium.py
  tests/test_components/test_source.py
  tidy3d/components/data/data_array.py
  tidy3d/components/medium.py
  tidy3d/components/source.py
Labels: 2.7

#1636 Various improvements to EME solver.
  tests/test_components/test_eme.py
  tests/test_plugins/test_adjoint.py
  tests/test_plugins/test_mode_solver.py
  tidy3d/__init__.py
  tidy3d/components/data/data_array.py
  tidy3d/components/data/sim_data.py
  tidy3d/components/eme/data/sim_data.py
  tidy3d/components/eme/grid.py
  tidy3d/components/eme/monitor.py
  tidy3d/components/eme/simulation.py
  tidy3d/components/eme/sweep.py
  tidy3d/components/types.py
  tidy3d/plugins/mode/mode_solver.py
  tidy3d/plugins/mode/solver.py
  tidy3d/web/api/webapi.py
Labels: 2.7, blocking

#1738 Add lossless Green2008 cSi and modify default SiO2 in material_library
  CHANGELOG.md
  docs/api/material_library.rst
  tests/test_package/test_material_library.py
  tidy3d/material_library/material_library.py
  tidy3d/plugins/dispersion/fit_fast.py
Labels: 2.7

#1719 Enable snapping_points in grid generation
  CHANGELOG.md
  tests/test_components/test_grid_spec.py
  tidy3d/components/grid/grid_spec.py
  tidy3d/components/grid/mesher.py
  tidy3d/components/simulation.py
Labels: 2.7

#1751 fix deepcopy bug in autograd
  tidy3d/components/base.py
  tidy3d/components/data/data_array.py
  tidy3d/components/geometry/polyslab.py
Labels: 2.7, .0, blocking

#1743 support for differentiation w.r.t. `CustomMedium.eps_dataset` components
  tests/test_components/test_autograd.py
  tidy3d/components/medium.py
Labels: 2.7

#1767 Fix doc on Courant number API
  docs/_static/img/courant_instability_2d.png
  tidy3d/components/simulation.py
Labels: 2.7

#1756 Introduced RF material library to microwave plugins
  CHANGELOG.md
  docs/api/index.rst
  docs/api/mediums.rst
  docs/api/rf_material_library.rst
  docs/generate_doc.py
  tidy3d/material_library/material_library.py
  tidy3d/material_library/material_reference.py
  tidy3d/plugins/microwave/__init__.py
  tidy3d/plugins/microwave/rf_material_library.py
  tidy3d/plugins/microwave/rf_material_reference.py
Labels: 2.8
