Repository flexcompute/tidy3d, pull requests merged in 2024-12, with the labels that each got.

#2096 Simplify interp validator
  tests/test_components/test_custom.py
  tidy3d/components/data/data_array.py
Labels: 2.8

#2098 Fix another geos error in _filter_structures_plane
  tidy3d/components/scene.py
Labels: Bug

#2028 automatic mode rotation for bent waveguide
  CHANGELOG.md
  tidy3d/__init__.py
  tidy3d/components/data/data_array.py
  tidy3d/components/data/dataset.py
  tidy3d/components/mode.py
  tidy3d/plugins/mode/mode_solver.py
Labels: 2.8

#2018 Add more robust gauge choice for high-order modes
  CHANGELOG.md
  tests/test_plugins/test_mode_solver.py
  tidy3d/plugins/mode/mode_solver.py
Labels: 2.8

#2110 Adding 'fields' argument to ModeSolver and ModeSolverMonitor
  CHANGELOG.md
  tests/test_plugins/test_mode_solver.py
  tidy3d/components/data/monitor_data.py
  tidy3d/components/monitor.py
  tidy3d/plugins/mode/mode_solver.py
Labels: rc1, 2.8

#2056 refactor gradient calculations to use `DerivativeSurfaceMesh`
  CHANGELOG.md
  tests/test_components/test_autograd.py
  tidy3d/components/autograd/derivative_utils.py
  tidy3d/components/geometry/polyslab.py
  tidy3d/components/geometry/primitives.py
  tidy3d/components/simulation.py
  tidy3d/components/structure.py
  tidy3d/plugins/autograd/README.md
  tidy3d/web/api/autograd/autograd.py
Labels: rc1, 2.8

#2135 Improve progress bar display in Batch operations
  CHANGELOG.md
  tidy3d/web/api/container.py
Labels: 2.8
