Repository flexcompute/tidy3d, pull requests merged in 2024-03, with the labels that each got.

#1513 fix adjoint "edge" case :P
  CHANGELOG.md
  tidy3d/plugins/adjoint/components/geometry.py
Labels: 2.6

#1519 Improve voltage computation for lumped ports
  tidy3d/plugins/smatrix/component_modelers/terminal.py
Labels: improvement

#1535 Modified zero-size validator
  CHANGELOG.md
  tests/test_components/test_heat.py
  tidy3d/components/heat/simulation.py
Labels: 2.7

#1558 Fix: port computations for coarse grids
  tests/test_plugins/terminal_component_modeler_def.py
  tests/test_plugins/test_terminal_component_modeler.py
  tidy3d/plugins/smatrix/component_modelers/terminal.py
Labels: Bug

#1554 Restrict number of time points for non-0D field time monitors
  CHANGELOG.md
  tests/test_components/test_simulation.py
  tidy3d/components/simulation.py
Labels: 2.7
