Repository flexcompute/tidy3d, pull requests merged in 2025-05, with the labels that each got.

#2398 Vasily/refinement_region_clean
  CHANGELOG.md
  tidy3d/__init__.py
  tidy3d/components/tcad/grid.py
Labels: Charge

#2432 Adding function NedeljkovicSorefMashanovich to docs
  docs/api/mediums.rst
Labels: Charge

#2437 Adding refinement regions to the docs
  docs/api/heat/discretization.rst
Labels: Charge

#2434 fix[frontend]: fix computation of finite axis length for PolySlab
  CHANGELOG.md
  tests/test_components/test_geometry.py
  tidy3d/components/geometry/polyslab.py
Labels: 2.8, .4

#2439 :paintbrush: Final touches for docs color scheme
  docs/_static/css/custom.css
  docs/index.rst
Labels: 2.8, .4

#2468 fix multiphysics medium attribute lookup
  tests/test_components/material/test_multi_physics.py
  tidy3d/components/material/multi_physics.py
Labels: 2.8, .4

#2474 fix tests in develop
  tests/test_components/test_layerrefinement.py
Labels: 2.9

#2485 fix: NedeljkovicSorefMashanovich serialization
  tests/test_components/test_parameter_perturbation.py
  tidy3d/components/data/data_array.py
  tidy3d/components/parameter_perturbation.py
Labels: 2.9

#2467 adding eps_lim argument to plot_eps
  CHANGELOG.md
  tidy3d/components/simulation.py
Labels: 2.9

#2492 Making all adjoint helpers private
  CHANGELOG.md
  tests/test_components/test_autograd.py
  tidy3d/components/base.py
  tidy3d/components/data/monitor_data.py
  tidy3d/components/data/sim_data.py
  tidy3d/components/geometry/base.py
  tidy3d/components/geometry/polyslab.py
  tidy3d/components/geometry/primitives.py
  tidy3d/components/grid/grid_spec.py
  tidy3d/components/medium.py
  tidy3d/components/simulation.py
  tidy3d/components/structure.py
  tidy3d/web/api/autograd/autograd.py
Labels: 2.9

#2500 Thin conductor thickness in LossyMetalMedium
  CHANGELOG.md
  tests/test_components/test_medium.py
  tidy3d/components/medium.py
Labels: rc1, 2.9, RF

#2336 Structure priority option in structure overlapping region
  CHANGELOG.md
  tests/test_components/test_scene.py
  tidy3d/components/base_sim/simulation.py
  tidy3d/components/grid/grid_spec.py
  tidy3d/components/lumped_element.py
  tidy3d/components/scene.py
  tidy3d/components/simulation.py
  tidy3d/components/structure.py
  tidy3d/components/tcad/simulation/heat_charge.py
  tidy3d/components/types.py
  tidy3d/plugins/adjoint/components/simulation.py
Labels: rc1, 2.9

#2476 Added resistance calculation
  tests/test_components/test_heat_charge.py
  tidy3d/components/spice/sources/dc.py
  tidy3d/components/tcad/data/sim_data.py
  tidy3d/components/tcad/simulation/heat_charge.py
Labels: rc1, 2.9, Charge

#2455 adjust adjoint source fwidth to decay before zero frequency when possible
  CHANGELOG.md
  tests/test_components/test_autograd.py
  tidy3d/components/data/sim_data.py
Labels: 2.9

#2447 Custom heat source
  tests/test_components/test_heat.py
  tests/test_web/test_webapi_heat.py
  tidy3d/components/tcad/simulation/heat_charge.py
  tidy3d/components/tcad/source/heat.py
Labels: rc1, 2.9, Charge

#2497 Allow kwargs to be used with autograd primitives
  CHANGELOG.md
  tests/test_plugins/autograd/primitives/test_interpolate.py
  tests/test_plugins/autograd/test_functions.py
  tidy3d/components/autograd/functions.py
  tidy3d/plugins/autograd/primitives/interpolate.py
Labels: 2.9

#2457 fix[web]: use dedicated endpoint for `web.delete_old()`
  CHANGELOG.md
  tests/test_web/test_webapi.py
  tidy3d/web/api/webapi.py
  tidy3d/web/core/task_core.py
Labels: 2.9
