Repository flexcompute/tidy3d, pull requests merged in 2025-03, with the labels that each got.

#2285 Simulation.grid_info property for important grid information
  CHANGELOG.md
  tests/test_components/test_simulation.py
  tidy3d/components/grid/grid.py
  tidy3d/components/simulation.py
Labels: 2.8

#2269 Refactored `bend_angle_rotation` to support general angle rotation
  CHANGELOG.md
  tests/sims/simulation_sample.h5
  tests/sims/simulation_sample.json
  tidy3d/components/mode/mode_solver.py
  tidy3d/components/mode_spec.py
Labels: 2.8

#2298 Minor docs change for FluidMedium and SolidMedium
  docs/api/heat/mediums.rst
  tidy3d/components/material/tcad/heat.py
Labels: 2.8

#2318 fix[web]: fix task querying
  CHANGELOG.md
  tidy3d/web/core/http_util.py
Labels: Bug

#2311 fix: automatically create batch output directories
  CHANGELOG.md
  tests/test_web/test_webapi.py
  tidy3d/web/api/container.py
Labels: Bug

#2323 chore: add dependency group for `design` plugin
  CHANGELOG.md
  docs/install.rst
  poetry.lock
  pyproject.toml
  tidy3d/plugins/design/method.py
Labels: 2.9

#2319 fix[adjoint]: fix tuple handling in autograd gradient calculations
  CHANGELOG.md
  tests/test_components/test_autograd.py
  tidy3d/web/api/autograd/autograd.py
Labels: Bug

#2326 Improve accuracy of normal E-field computation in mode solver
  CHANGELOG.md
  tidy3d/components/mode/solver.py
Labels: Charge

#2328 fix: deletion of tasks using `web.delete(task_id)`
  CHANGELOG.md
  tests/test_web/test_webapi.py
  tidy3d/web/api/webapi.py
  tidy3d/web/core/http_util.py
  tidy3d/web/core/task_core.py
Labels: Bug

#2242 Adding option for Fermi-Dirac statistics
  CHANGELOG.md
  tests/test_components/test_heat_charge.py
  tidy3d/components/spice/analysis/dc.py
Labels: Charge

#2297 Add ContourPath averaging option to dielectric subpixel
  CHANGELOG.md
  docs/api/subpixel_averaging.rst
  tidy3d/__init__.py
  tidy3d/components/subpixel_spec.py
Labels: awaiting backend
