Repository flexcompute/tidy3d, pull requests merged in 2025-08, with the labels that each got.

#2700 Validate the number of grid points on modal plane
  CHANGELOG.md
  tests/test_plugins/test_mode_solver.py
  tidy3d/components/mode/mode_solver.py
Labels: 2.9

#2708 RF development staging
  CHANGELOG.md
  schemas/TerminalComponentModeler.json
  tests/test_plugins/smatrix/terminal_component_modeler_def.py
  tests/test_plugins/smatrix/test_component_modeler.py
  tests/test_plugins/smatrix/test_terminal_component_modeler.py
  tidy3d/plugins/smatrix/component_modelers/base.py
  tidy3d/plugins/smatrix/component_modelers/modal.py
  tidy3d/plugins/smatrix/component_modelers/terminal.py
Labels: RF

#2650 improve support for lossy transmission lines and complex reference impedances
  CHANGELOG.md
  schemas/EMESimulation.json
  schemas/ModeSimulation.json
  schemas/Simulation.json
  schemas/TerminalComponentModeler.json
  tests/test_plugins/smatrix/test_terminal_component_modeler.py
  tidy3d/components/monitor.py
  tidy3d/plugins/smatrix/component_modelers/terminal.py
  tidy3d/plugins/smatrix/ports/wave.py
Labels: RF

#2732 revert overly strict validation of 'freqs'
  CHANGELOG.md
  tests/test_plugins/smatrix/test_terminal_component_modeler.py
  tidy3d/components/validators.py
  tidy3d/plugins/smatrix/component_modelers/base.py
  tidy3d/plugins/smatrix/component_modelers/terminal.py
Labels: Bug

#2733 fix bug in TerminalComponentModeler.get_antenna_metrics_data
  CHANGELOG.md
  tests/test_plugins/smatrix/test_terminal_component_modeler.py
  tidy3d/plugins/smatrix/component_modelers/terminal.py
Labels: Bug

#2651 [FXC-1504]: Adding support for current density monitor
  schemas/HeatChargeSimulation.json
  schemas/HeatSimulation.json
  schemas/TerminalComponentModeler.json
  tests/test_components/test_heat_charge.py
  tidy3d/__init__.py
  tidy3d/components/tcad/data/monitor_data/abstract.py
  tidy3d/components/tcad/data/monitor_data/charge.py
  tidy3d/components/tcad/data/monitor_data/heat.py
  tidy3d/components/tcad/data/monitor_data/mesh.py
  tidy3d/components/tcad/data/types.py
  tidy3d/components/tcad/monitors/charge.py
  tidy3d/components/tcad/simulation/heat_charge.py
  tidy3d/components/tcad/types.py
Labels: Charge

#2696 feat: Add natural convection BC
  CHANGELOG.md
  schemas/EMESimulation.json
  schemas/HeatChargeSimulation.json
  schemas/HeatSimulation.json
  schemas/ModeSimulation.json
  schemas/Simulation.json
  schemas/TerminalComponentModeler.json
  tests/test_components/test_heat.py
  tests/test_components/test_heat_charge.py
  tidy3d/__init__.py
  tidy3d/components/material/tcad/heat.py
  tidy3d/components/tcad/boundary/heat.py
  tidy3d/components/tcad/simulation/heat_charge.py
  tidy3d/components/tcad/types.py
  tidy3d/constants.py
Labels: Charge
