Repository flexcompute/tidy3d, pull requests merged in 2025-02, with the labels that each got.

#2220 A meshing bug that skips the domain coordinate
  tests/test_components/test_grid_spec.py
  tidy3d/components/grid/mesher.py
Labels: Bug

#2231 :zap: Fossum model for carrier lifetime
  tests/test_components/test_heat_charge.py
  tidy3d/__init__.py
  tidy3d/components/material/multi_physics.py
  tidy3d/components/material/tcad/charge.py
  tidy3d/components/tcad/generation_recombination.py
  tidy3d/components/tcad/mobility.py
  tidy3d/material_library/material_library.py
Labels: Charge

#2239 :zap: Fix normal axis in doping
  tidy3d/components/tcad/doping.py
Labels: Charge

#2241 Support for automatically running multiple adjoint simulations from single fwd
  CHANGELOG.md
  tests/test_components/test_autograd.py
  tidy3d/components/data/data_array.py
  tidy3d/components/data/sim_data.py
  tidy3d/plugins/autograd/README.md
  tidy3d/web/api/autograd/autograd.py
Labels: 2.8

#2260 Add folder_name for the task GUI link.
  CHANGELOG.md
  tidy3d/web/api/webapi.py
  tidy3d/web/core/task_core.py
Labels: 2.8

#2266 Fix to _interpolated_tangential_fields when data has only one coordinate
  tidy3d/components/data/monitor_data.py
Labels: 2.8

#2267 :wrench: fix common typo in docstring links
  CHANGELOG.md
  tidy3d/components/base_sim/simulation.py
  tidy3d/components/data/data_array.py
  tidy3d/components/data/unstructured/tetrahedral.py
  tidy3d/components/eme/simulation.py
  tidy3d/components/field_projection.py
  tidy3d/components/lumped_element.py
  tidy3d/components/mode/mode_solver.py
  tidy3d/components/simulation.py
  tidy3d/components/tcad/simulation/heat_charge.py
Labels: 2.8

#2263 Improve meshing and snapping points in lumped elements
  CHANGELOG.md
  tests/test_components/test_layerrefinement.py
  tests/test_components/test_lumped_element.py
  tests/test_components/test_simulation.py
  tests/test_plugins/smatrix/terminal_component_modeler_def.py
  tests/test_plugins/smatrix/test_terminal_component_modeler.py
  tidy3d/components/grid/grid_spec.py
  tidy3d/components/lumped_element.py
  tidy3d/components/simulation.py
  tidy3d/plugins/smatrix/component_modelers/terminal.py
  tidy3d/plugins/smatrix/ports/base_lumped.py
  tidy3d/plugins/smatrix/ports/coaxial_lumped.py
  tidy3d/plugins/smatrix/ports/rectangular_lumped.py
Labels: 2.8

#2190 add antenna gain and efficiency figures of merit
  CHANGELOG.md
  docs/api/index.rst
  docs/api/microwave/index.rst
  docs/api/microwave/output_data.rst
  docs/api/plugins/smatrix.rst
  tests/test_components/test_microwave.py
  tests/test_data/test_data_arrays.py
  tests/test_data/test_monitor_data.py
  tests/test_plugins/smatrix/test_terminal_component_modeler.py
  tests/utils.py
  tidy3d/__init__.py
  tidy3d/components/data/monitor_data.py
  tidy3d/components/microwave/data/__init__.py
  tidy3d/components/microwave/data/monitor_data.py
  tidy3d/components/types.py
  tidy3d/plugins/smatrix/__init__.py
  tidy3d/plugins/smatrix/component_modelers/base.py
  tidy3d/plugins/smatrix/component_modelers/terminal.py
  tidy3d/plugins/smatrix/data/__init__.py
  tidy3d/plugins/smatrix/data/terminal.py
  tidy3d/plugins/smatrix/ports/base_terminal.py
Labels: 2.8

#2228 Array factor
  CHANGELOG.md
  tests/test_plugins/test_array_factor.py
  tidy3d/components/simulation.py
  tidy3d/plugins/microwave/__init__.py
  tidy3d/plugins/microwave/array_factor.py
Labels: 2.8

#2278 More robust float number comparison in Mesher.filter_min_step
  tidy3d/components/grid/mesher.py
Labels: Bug, 2.8

#2273 Update spice.rst
  docs/api/spice.rst
Labels: 2.8

#2281 Use `bayes_opt<2`
  poetry.lock
  pyproject.toml
Labels: 2.8

#2268 Co- and cross-polarization for linear polarization
  CHANGELOG.md
  tests/test_components/test_microwave.py
  tidy3d/components/data/monitor_data.py
  tidy3d/components/microwave/data/monitor_data.py
Labels: 2.8

#2274 Added validation for the monitors frequency range to be consistent with the frequency range defined by the sources.
  CHANGELOG.md
  tests/test_components/test_simulation.py
  tests/test_package/test_log.py
  tidy3d/components/simulation.py
Labels: 2.8

#2282 Fix adjoint source creation
  CHANGELOG.md
  tidy3d/web/api/autograd/autograd.py
Labels: 2.8

#2287 refc[adjoint]: filter zero VJPs in setup_adj
  tests/test_components/test_autograd.py
  tidy3d/web/api/autograd/autograd.py
Labels: 2.8
