Repository flexcompute/tidy3d, pull requests merged in 2025-04, with the labels that each got.

#2348 Fix polyslab tests and add interior_angle property to PolySlab
  CHANGELOG.md
  tests/test_components/test_sidewall.py
  tidy3d/components/geometry/polyslab.py
Labels: Bug

#2312 Convenience function to add charge perturbations with Nedeljkovic Soref Mashanovich model
  tests/test_components/test_parameter_perturbation.py
  tidy3d/__init__.py
  tidy3d/components/parameter_perturbation.py
Labels: Charge

#2352 fix[adjoint]: Pass correct frequency for epsilon calculation in adjoint postprocessing
  CHANGELOG.md
  tests/test_components/test_autograd.py
  tidy3d/web/api/autograd/autograd.py
Labels: Bug

#2343 fix[testing]: fixed test_geometry bounds checking tests
  tests/test_components/test_geometry.py
Labels: 2.8, .2

#2338 Correct scaling for adjoint sources created from field monitors
  CHANGELOG.md
  pyproject.toml
  tests/conftest.py
  tests/test_components/test_autograd_numerical.py
  tests/test_components/test_viz.py
  tidy3d/components/data/monitor_data.py
  tidy3d/components/grid/grid.py
Labels: 2.8, .2

#2383 SemiconductorMedium used directly as medium in Charge simulations
  tidy3d/components/tcad/simulation/heat_charge.py
Labels: Charge

#2384 Change return values to None instead of ValueError
  tidy3d/components/material/tcad/charge.py
  tidy3d/components/medium.py
  tidy3d/components/tcad/simulation/heat_charge.py
Labels: Charge

#2400 fix[tests]: fix resource locking in adjoint plugin tests
  tests/test_plugins/test_adjoint.py
Labels: 2.8, .3

#2399 fix[autograd]: add boolean flag indicating adjoint runs
  tidy3d/web/api/autograd/autograd.py
Labels: 2.8, .3

#2386 fix[adjoint]: remove frequency summing in polyslab gradient calculation
  CHANGELOG.md
  tests/test_components/test_autograd_mode_polyslab_numerical.py
  tests/test_components/test_autograd_numerical.py
  tidy3d/components/autograd/derivative_utils.py
  tidy3d/components/geometry/base.py
  tidy3d/web/api/autograd/autograd.py
Labels: Bug, 2.8, .3

#2344 Vasily/bandgap_monitor_update
  tests/test_components/test_heat_charge.py
  tidy3d/__init__.py
  tidy3d/components/tcad/data/monitor_data/charge.py
  tidy3d/components/tcad/data/types.py
  tidy3d/components/tcad/monitors/charge.py
  tidy3d/components/tcad/types.py
Labels: Charge

#2401 enh[web]: make pay type selection case insensitive
  tests/test_web/test_tidy3d_task.py
  tidy3d/web/api/asynchronous.py
  tidy3d/web/api/autograd/autograd.py
  tidy3d/web/api/mode.py
  tidy3d/web/api/webapi.py
  tidy3d/web/core/task_core.py
  tidy3d/web/core/types.py
Labels: 2.8, .3
