Repository flexcompute/tidy3d, pull requests merged in 2025-01, with the labels that each got.

#2058 Use default `td.ModeSpec` in mode monitors
  CHANGELOG.md
  tests/test_components/test_monitor.py
  tidy3d/components/monitor.py
Labels: 2.8

#2087 Minimum install for tidy3d
  tidy3d/components/autograd/functions.py
  tidy3d/components/data/data_array.py
  tidy3d/components/data/dataset.py
  tidy3d/components/eme/simulation.py
  tidy3d/components/geometry/base.py
  tidy3d/components/geometry/polyslab.py
  tidy3d/components/heat_charge/simulation.py
  tidy3d/components/parameter_perturbation.py
  tidy3d/components/scene.py
  tidy3d/components/simulation.py
  tidy3d/components/types.py
  tidy3d/components/viz.py
Labels: 2.8

#2161 fix[invdes]: handle pixel size validation for simulations without sources
  CHANGELOG.md
  tests/test_plugins/test_invdes.py
  tidy3d/plugins/invdes/validators.py
Labels: 2.8

#2159 Fix gradient magnitude custom medium
  CHANGELOG.md
  tidy3d/components/medium.py
Labels: 2.8

#2163 feat[frontend]: add angle validator to specify expected angle in radians
  CHANGELOG.md
  tidy3d/components/geometry/base.py
Labels: 2.8

#2170 feat: Add autograd support for PolySlab transformations
  CHANGELOG.md
  tests/test_components/test_autograd.py
  tidy3d/components/geometry/polyslab.py
  tidy3d/components/transformation.py
Labels: 2.8

#2174 Fix AutoGrid to use full sim_size for computing dl_max
  tidy3d/components/grid/grid_spec.py
Labels: Bug

#2191 fix[autograd]: ensure consistent task name mapping for batch autograd
  CHANGELOG.md
  tests/test_components/test_autograd.py
  tidy3d/web/api/autograd/autograd.py
Labels: Bug

#2204 Update error handling in webapi, and Heat->HeatCharge in message
  tidy3d/components/tcad/data/monitor_data/charge.py
  tidy3d/web/api/webapi.py
  tidy3d/web/core/constants.py
  tidy3d/web/core/task_core.py
Labels: Charge

#2205 Constant doping box foxed
  tests/test_components/test_heat_charge.py
  tidy3d/components/scene.py
  tidy3d/components/tcad/doping.py
Labels: Charge

#2199 :wrench: fix duplicate web folders
  CHANGELOG.md
  tidy3d/web/api/container.py
Labels: Bug

#2212 Doping 0-size message and bugs
  tests/test_components/test_heat_charge.py
  tidy3d/components/material/tcad/charge.py
  tidy3d/components/scene.py
  tidy3d/components/tcad/doping.py
Labels: Charge
