Repository flexcompute/tidy3d, pull requests merged in 2025-06, with the labels that each got.

#2514 Adding heat, charge and conduction simulations to test/utils.py
  scripts/sample.py
  tests/sims/full_charge.h5
  tests/sims/full_charge.json
  tests/sims/full_conduction.h5
  tests/sims/full_conduction.json
  tests/sims/full_fdtd.h5
  tests/sims/full_fdtd.json
  tests/sims/full_steady_heat.h5
  tests/sims/full_steady_heat.json
  tests/sims/full_unsteady_heat.h5
  tests/sims/full_unsteady_heat.json
  tests/test_components/test_IO.py
  tests/utils.py
Labels: Charge

#2524 Adding monitor validations for Conduction simulations
  tests/test_components/test_heat.py
  tests/test_components/test_heat_charge.py
  tidy3d/components/tcad/simulation/heat_charge.py
Labels: Charge

#2553 Automatically use periodic boundary on zero-size dimensions
  CHANGELOG.md
  tests/test_components/test_mode.py
  tests/test_components/test_simulation.py
  tidy3d/components/eme/simulation.py
  tidy3d/components/mode/simulation.py
  tidy3d/components/simulation.py
Labels: 2.9

#2558 Determining zero dimesnions in slices
  tidy3d/components/data/unstructured/triangular.py
Labels: Charge, Heat

#2583 Fix to mode solver simulation reduction in web.upload
  tests/test_web/test_webapi_mode.py
  tests/test_web/test_webapi_mode_sim.py
  tidy3d/web/api/webapi.py
Labels: rc2, 2.9

#2597 Adding some missing classes
  docs/api/charge/mediums.rst
  docs/api/mediums.rst
  docs/api/spice.rst
  tidy3d/components/tcad/boundary/charge.py
Labels: Charge

#2585 refc[adjoint]: Refactor PoleResidue derivative calculation
  CHANGELOG.md
  tests/test_components/test_autograd.py
  tidy3d/components/medium.py
Labels: rc2, 2.9
