Repository flexcompute/tidy3d, pull requests merged in 2025-07, with the labels that each got.

#2566 Electric field monitor for Charge
  tests/test_components/test_heat_charge.py
  tidy3d/__init__.py
  tidy3d/components/data/data_array.py
  tidy3d/components/data/unstructured/base.py
  tidy3d/components/tcad/data/monitor_data/charge.py
  tidy3d/components/tcad/data/types.py
  tidy3d/components/tcad/monitors/charge.py
  tidy3d/components/tcad/types.py
Labels: rc2, 2.9, Charge

#2502 Enable bulk PMC material
  CHANGELOG.md
  docs/api/mediums.rst
  tests/test_components/material/test_multi_physics.py
  tests/test_components/test_medium.py
  tests/test_components/test_time_modulation.py
  tests/utils.py
  tidy3d/__init__.py
  tidy3d/components/material/multi_physics.py
  tidy3d/components/medium.py
  tidy3d/components/mode/mode_solver.py
  tidy3d/components/scene.py
  tidy3d/components/simulation.py
  tidy3d/components/subpixel_spec.py
Labels: rc2, 2.9

#2658 ci: forbid module-level import of scipy & matplotlib
  pyproject.toml
  tidy3d/components/mode/mode_solver.py
  tidy3d/components/viz/axes_utils.py
Labels: rc2, 2.9

#2675 Fix small error in doping computation
  tidy3d/components/tcad/doping.py
Labels: Charge

#2677 Fix unsteady heat test
  tests/test_components/test_heat_charge.py
  tidy3d/components/tcad/simulation/heat_charge.py
Labels: Charge

#2666 Add check for conduction
  CHANGELOG.md
  tests/test_components/test_heat_charge.py
  tidy3d/components/tcad/simulation/heat_charge.py
Labels: Charge

#2682 Giving opposite boundaries different names no longer causes a symmetry validator failure
  CHANGELOG.md
  tests/test_components/test_simulation.py
  tidy3d/components/simulation.py
Labels: Bug

#2657 Add support for uniform frequency and wavelength sampling in freqs() and ldas()
  tests/test_components/test_freq_range.py
  tests/test_components/test_frequencies.py
  tidy3d/__init__.py
  tidy3d/components/frequencies.py
  tidy3d/components/source/freq_range.py
Labels: 2.9

#2693 fix: multifrequency adjoint performance by vectorizing over frequencies
  CHANGELOG.md
  tests/test_components/test_autograd.py
  tests/test_components/test_autograd_polyslab.py
  tidy3d/components/autograd/constants.py
  tidy3d/components/autograd/derivative_utils.py
  tidy3d/components/data/monitor_data.py
  tidy3d/components/geometry/base.py
  tidy3d/components/geometry/primitives.py
  tidy3d/components/medium.py
  tidy3d/web/api/autograd/autograd.py
Labels: 2.9
